#!/bin/bash

set st = `git status --porcelain`
if [ -n "$st" ] ; then
    echo "Please commit uncommitted state first:"; \
    git status
fi

git checkout master &&
git pull &&
git checkout local &&
git rebase master &&
git checkout master &&
git merge local &&
git push &&
git checkout local
